// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/watchpost.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_proto_watchpost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchpost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_proto_watchpost_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Service) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Service) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Service) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

type GetServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesRequest) Reset() {
	*x = GetServicesRequest{}
	mi := &file_proto_watchpost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesRequest) ProtoMessage() {}

func (x *GetServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchpost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesRequest.ProtoReflect.Descriptor instead.
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchpost_proto_rawDescGZIP(), []int{1}
}

type GetServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesResponse) Reset() {
	*x = GetServicesResponse{}
	mi := &file_proto_watchpost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesResponse) ProtoMessage() {}

func (x *GetServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchpost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesResponse.ProtoReflect.Descriptor instead.
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchpost_proto_rawDescGZIP(), []int{2}
}

func (x *GetServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type WatchStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStatusRequest) Reset() {
	*x = WatchStatusRequest{}
	mi := &file_proto_watchpost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatusRequest) ProtoMessage() {}

func (x *WatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchpost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchpost_proto_rawDescGZIP(), []int{3}
}

var File_proto_watchpost_proto protoreflect.FileDescriptor

const file_proto_watchpost_proto_rawDesc = "" +
	"\n" +
	"\x15proto/watchpost.proto\x12\twatchpost\"\x89\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\tR\tcheckedAt\"\x14\n" +
	"\x12GetServicesRequest\"E\n" +
	"\x13GetServicesResponse\x12.\n" +
	"\bservices\x18\x01 \x03(\v2\x12.watchpost.ServiceR\bservices\"\x14\n" +
	"\x12WatchStatusRequest2\x9d\x01\n" +
	"\tWatchpost\x12L\n" +
	"\vGetServices\x12\x1d.watchpost.GetServicesRequest\x1a\x1e.watchpost.GetServicesResponse\x12B\n" +
	"\vWatchStatus\x12\x1d.watchpost.WatchStatusRequest\x1a\x12.watchpost.Service0\x01B%Z#github.com/gappylul/watchpost/protob\x06proto3"

var (
	file_proto_watchpost_proto_rawDescOnce sync.Once
	file_proto_watchpost_proto_rawDescData []byte
)

func file_proto_watchpost_proto_rawDescGZIP() []byte {
	file_proto_watchpost_proto_rawDescOnce.Do(func() {
		file_proto_watchpost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_watchpost_proto_rawDesc), len(file_proto_watchpost_proto_rawDesc)))
	})
	return file_proto_watchpost_proto_rawDescData
}

var file_proto_watchpost_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_watchpost_proto_goTypes = []any{
	(*Service)(nil),             // 0: watchpost.Service
	(*GetServicesRequest)(nil),  // 1: watchpost.GetServicesRequest
	(*GetServicesResponse)(nil), // 2: watchpost.GetServicesResponse
	(*WatchStatusRequest)(nil),  // 3: watchpost.WatchStatusRequest
}
var file_proto_watchpost_proto_depIdxs = []int32{
	0, // 0: watchpost.GetServicesResponse.services:type_name -> watchpost.Service
	1, // 1: watchpost.Watchpost.GetServices:input_type -> watchpost.GetServicesRequest
	3, // 2: watchpost.Watchpost.WatchStatus:input_type -> watchpost.WatchStatusRequest
	2, // 3: watchpost.Watchpost.GetServices:output_type -> watchpost.GetServicesResponse
	0, // 4: watchpost.Watchpost.WatchStatus:output_type -> watchpost.Service
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_watchpost_proto_init() }
func file_proto_watchpost_proto_init() {
	if File_proto_watchpost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_watchpost_proto_rawDesc), len(file_proto_watchpost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_watchpost_proto_goTypes,
		DependencyIndexes: file_proto_watchpost_proto_depIdxs,
		MessageInfos:      file_proto_watchpost_proto_msgTypes,
	}.Build()
	File_proto_watchpost_proto = out.File
	file_proto_watchpost_proto_goTypes = nil
	file_proto_watchpost_proto_depIdxs = nil
}
