// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/watchpost.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Watchpost_GetServices_FullMethodName = "/watchpost.Watchpost/GetServices"
	Watchpost_WatchStatus_FullMethodName = "/watchpost.Watchpost/WatchStatus"
)

// WatchpostClient is the client API for Watchpost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchpostClient interface {
	GetServices(ctx context.Context, in *GetServicesRequest, opts ...grpc.CallOption) (*GetServicesResponse, error)
	WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error)
}

type watchpostClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchpostClient(cc grpc.ClientConnInterface) WatchpostClient {
	return &watchpostClient{cc}
}

func (c *watchpostClient) GetServices(ctx context.Context, in *GetServicesRequest, opts ...grpc.CallOption) (*GetServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServicesResponse)
	err := c.cc.Invoke(ctx, Watchpost_GetServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchpostClient) WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Watchpost_ServiceDesc.Streams[0], Watchpost_WatchStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStatusRequest, Service]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Watchpost_WatchStatusClient = grpc.ServerStreamingClient[Service]

// WatchpostServer is the server API for Watchpost service.
// All implementations must embed UnimplementedWatchpostServer
// for forward compatibility.
type WatchpostServer interface {
	GetServices(context.Context, *GetServicesRequest) (*GetServicesResponse, error)
	WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[Service]) error
	mustEmbedUnimplementedWatchpostServer()
}

// UnimplementedWatchpostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchpostServer struct{}

func (UnimplementedWatchpostServer) GetServices(context.Context, *GetServicesRequest) (*GetServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServices not implemented")
}
func (UnimplementedWatchpostServer) WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[Service]) error {
	return status.Error(codes.Unimplemented, "method WatchStatus not implemented")
}
func (UnimplementedWatchpostServer) mustEmbedUnimplementedWatchpostServer() {}
func (UnimplementedWatchpostServer) testEmbeddedByValue()                   {}

// UnsafeWatchpostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchpostServer will
// result in compilation errors.
type UnsafeWatchpostServer interface {
	mustEmbedUnimplementedWatchpostServer()
}

func RegisterWatchpostServer(s grpc.ServiceRegistrar, srv WatchpostServer) {
	// If the following call panics, it indicates UnimplementedWatchpostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Watchpost_ServiceDesc, srv)
}

func _Watchpost_GetServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchpostServer).GetServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Watchpost_GetServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchpostServer).GetServices(ctx, req.(*GetServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watchpost_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WatchpostServer).WatchStatus(m, &grpc.GenericServerStream[WatchStatusRequest, Service]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Watchpost_WatchStatusServer = grpc.ServerStreamingServer[Service]

// Watchpost_ServiceDesc is the grpc.ServiceDesc for Watchpost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Watchpost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchpost.Watchpost",
	HandlerType: (*WatchpostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServices",
			Handler:    _Watchpost_GetServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _Watchpost_WatchStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/watchpost.proto",
}
